site_name: Documentation
theme: 
  name: material
  custom_dir: theme_override
  favicon: 'img/favicon-v2.png'
  logo: 'img/logo.png'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/flo-blockchain'
    - type: 'twitter'
      link: 'https://twitter.com/floblockchain'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/floblockchain/'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCDAELSdJelys5VkE1FuXo2A'
site_url: https://flo.cash
repo_url: https://github.com/valentinjesse/flodocs
repo_name: valentinjesse/flodocs
markdown_extensions:
  - footnotes
  - fontawesome_markdown
  - smarty
  - mdx_math
  - toc:
      permalink: True
  - tables
extra_javascript:
  - js/MathJax-2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
    - css/style.css
pages:
- 'Home': 'index.md'
- Getting Started:
  - 'Obtaining FLO': 'getting-started/obtaining-flo.md'
  - 'FLO Setup': 'getting-started/user-guides/flo-setup.md'

# - Wallets:
#     - FLO (GUI):
#       - 'FLO Setup': 'getting-started/user-guides/decrediton-setup.md'
#       - 'Using FLO': 'getting-started/user-guides/using-decrediton.md'
#     - CLI Wallet:
#       - 'Installation': 'getting-started/user-guides/cli-installation.md'
#       - 'OS Differences': 'getting-started/cli-differences.md'
#       - 'Startup Basics': 'getting-started/startup-basics.md'
#       - 'flod Setup': 'getting-started/user-guides/dcrd-setup.md'
#       - 'flowallet Setup': 'getting-started/user-guides/dcrwallet-setup.md'
#       - 'floctl Basics': 'getting-started/user-guides/dcrctl-basics.md'
#     - 'Web Wallet': 'getting-started/user-guides/web.md'

# - Proof-of-Work Mining:
#   - 'Overview': 'mining/proof-of-work.md'
#   - 'gominer Pool Mining': 'mining/proof-of-work/pool-mining/gominer.md'
#   - 'PoW FAQ': 'faq/proof-of-work-mining.md'
# - FAQ:
#   - 'General': 'faq/general.md'
#   - 'Configuration': 'faq/configuration.md'
#   - 'Wallets and Seeds': 'faq/wallets-and-seeds.md'
#   - 'Web Client': 'faq/web-client.md'
#   - 'Blocks': 'faq/blocks.md'

# - Research:
#   - 'Overview': 'research/overview.md'
#   - 'Elliptic Curve Signature Algorithms': 'research/elliptic-curve-signature-algorithms.md'
#   - 'BLAKE-256 Hash Function': 'research/blake-256-hash-function.md'
#   - 'Script Extensions': 'research/script-extensions.md'
#   - 'Signature Script Isolation and Fraud Proofs': 'research/signature-script-isolation-and-fraud-proofs.md'
#   - 'Transaction Extensions': 'research/transaction-extensions.md'
#   - 'Schnorr Signatures': 'research/schnorr-signatures.md'
  # - 'Miscellaneous Improvements': 'research/miscellaneous-improvements.md'
# - Contributing:
#   - 'Contributor Compensation': 'advanced/contributor-compensation.md'
#   - 'Contributor Projects': 'advanced/user-projects.md'
#   - Guidelines:
#     - 'Using GitHub': 'advanced/using-github.md'
#     - 'Source Code Contributions': 'advanced/contributing.md'

- Building Dapps:
    - 'Flotorizer.net': 'building-dapps/flotorizer.net.md'

- About:
  - 'Support Directory': 'support-directory.md'
#   - 'Credits': 'about/credits.md'
#   - 'License': 'about/license.md'

copyright: If you wish to improve this site, please <a href="https://github.com/valentinjesse/flodocs/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/valentinjesse/flodocs/compare"><i class="fa fa-github"></i> send a pull request</a>.<br>flodocs v0.0.1. FLO Project 2017.
